### ISSUE TITLE
Branding API doesn't support commas

### ISSUE THREAD

**Issue by brendony** [apigovau/api-gov-au#15]
I want to generate a logo for "Department of Education, Skills and Employment".

As far as I can tell, the api at https://api.gov.au/service/5bd921345149e90004f326a7 does not support text with a comma in it. My text comes out like this:

> Department of Education
> Skills and Employment

To reproduce, see here:
https://api-gov-au-crest-branding.apps.y.cld.gov.au/inline.png?agency=Department+of+A,+B+and+C&height=200

Using the %2C code produces identical results

**Comment by colugo** [comment]
Hi @brendony thanks for reaching out.

The web framework I'm using for this, Spring Boot, seems to have an unresolved bug that interprets commas in url params as list delimiters, but only when the controller method is configured to allow multiple values for the same key (as I do here for the list of agencies).

The unresolved bug goes back to 2014, and is unlikely to be fixed anytime soon, so I've custom built a workaround for you.

If you use $ instead of % for any UTF-8 characters, they'll get passed the Spring Boot bug, and I'll decode them inside the controller method.

Here's your example, with the workaround  

`https://api-gov-au-crest-branding.apps.y.cld.gov.au/inline.png?agency=Department+of+A$2c+B+and+C&height=200 `

![crest image with comma](https://api-gov-au-crest-branding.apps.y.cld.gov.au/inline.png?agency=Department+of+A$2c+B+and+C&height=200)

Alastair

**Comment by brendony** [comment]
Hi Alastair, thanks! Much appreciated
